#!/bin/bash



# /Fd"x64\Debug\vc142.pdb"
# /Fa"x64\Debug\"
# /Fo"x64\Debug\"
# /Fp"x64\Debug\Dll1.pch"
# /ifcOutput"x64\Debug\"


/JMC
/permissive-

/GS
/W3
/Zc:wchar_t
/ZI
/Gm-
/Od
/sdl
/Zc:inline
/fp:precise
/errorReport:prompt
/WX-
/Zc:forScope
/RTC1
/Gd

/MTd

/FC
/EHsc
/nologo

/diagnostics:column
